# Generated by Django 2.2 on 2019-05-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='zip code'),
        ),
    ]
