# Generated by Django 2.2 on 2019-05-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_auto_20190502_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'product')},
        ),
    ]
