# Generated by Django 2.2 on 2019-12-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191211_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermsissons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_update_products', models.BooleanField(default=False)),
                ('can_update_brands', models.BooleanField(default=False)),
                ('can_add_admins', models.BooleanField(default=False)),
                ('can_remove_admins', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permsissons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
