# Generated by Django 2.2 on 2019-12-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userpermsissons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPermsissons',
            new_name='UserPermissions',
        ),
    ]
