# Generated by Django 2.2 on 2019-12-15 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191215_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', related_query_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
