# Generated by Django 2.2 on 2019-05-01 12:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'sub category',
                'verbose_name_plural': 'sub categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_ar', models.CharField(max_length=50, verbose_name='name in arabic')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(verbose_name='description in arabic')),
                ('colors', models.TextField(help_text='Comma seperated list of available colors', validators=[django.core.validators.RegexValidator('^((\\w)+,)*\\w+$')], verbose_name='available colors')),
                ('colors_ar', models.TextField(help_text='Comma seperated list of available colors in arabic', validators=[django.core.validators.RegexValidator('^(([\\u0621-\\u064a])+,)*[\\u0621-\\u064a]+$')], verbose_name='available colors in arabic')),
                ('image', models.ImageField(help_text='Main image for the product', upload_to=products.models.get_upload_path, verbose_name='main image')),
                ('price', models.FloatField(verbose_name='price')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='sku')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('sizes', models.TextField(blank=True, help_text='Comma seperated list of available sizes', null=True, validators=[django.core.validators.RegexValidator('^(\\d+,)*\\d+$')], verbose_name='size')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='products', to='products.Brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='products', to='products.Category', verbose_name='category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='products', to='products.SubCategory', verbose_name='sub category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.get_upload_path, verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='images', to='products.Product', verbose_name='product')),
            ],
        ),
    ]
