# Generated by Django 2.2 on 2019-12-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(default='name in arabic', max_length=50, verbose_name='name in arabic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default='name', max_length=50, verbose_name='name in arabic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='image', to='products.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='image',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='image', to='products.SubCategory', verbose_name='sub category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='categories',
            field=models.ManyToManyField(related_name='sub_categories', to='products.Category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ar',
            field=models.CharField(default='name', max_length=50, verbose_name='name in arabic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='images', to='products.Product', verbose_name='product'),
        ),
    ]
